# Generated by Django 3.1.6 on 2021-02-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESEA_core', '0003_remove_organisation_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='organisations',
        ),
        migrations.AlterUniqueTogether(
            name='userorganisation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userorganisation',
            name='organisation',
        ),
    ]
